Python for Neuroscience
===========================

## What is Python?

Named after Monty Python's Flying Circus

![MP](http://cdn-5.fanaru.com/monty-pythons-flying-circus/image/69206-monty-pythons-flying-circus-flying-circus-wallpaper.jpg)


In [ ]:
import this

## Interfaces

### Terminal
- Comes with every mac

### Spyder
- A Matlab-like layout

### Jupyter notebook
- jupyter = JUlia + PYthon + R

A web based IDE that supports over 15 languages

+ composed of "cells" (code, markdown, raw, heading)
+ execute cells with "shift" + "return"
+ undo ("command" - z)
+ save checkpoint
+ keyboard shortcuts with "h"

### Using Markdown
Super fancy comments

# Big Header
## Smaller Header
### Even Smaller Header
#### etc...

Font choices:

**Bold** or __Bold__  
*Italic* or _Italic_  

You can make lists:
- list item1
- list item2
or
1. list item1
2. list item2

**Links**  
[Scale of Universe](http://scaleofuniverse.com/)

**Images**  
![Dream Brain](http://3.bp.blogspot.com/-QvwoLucHm7w/VawNRtOlB_I/AAAAAAAAKzQ/5CjRwDjKMRQ/s1600/HoffmansBicyle%2Bchalk%2Bdrawing%2Bdeep%2Bdream%2Bbrain.jpg)

LaTex compatible!

$\binom{n}{k} = \frac{n!}{k!(n-k)!}$

## Python Basics: Comments & Numbers

In [4]:
# A single line comment
""" A multiline comment
starts and ends
with three quotes, which also returns a multiline string"""


' A multiline comment\nstarts and ends\nwith three quotes, which also returns a multiline string'

Numbers behave pretty much the way you expect

In [2]:
2 + 2

4

In [3]:
4 * 8

32

In [4]:
4 * 8 + 2

34

In [5]:
4 * (8 + 2)

40

The `**` operator is used for exponents

In [6]:
2**8

256

If you're using Python 2, division can be a source for errors.

At the begining of every Python 2 script, be sure to include:

In [ ]:
from __future__ import division

In [6]:
5 / 2

2.5

Use `//` for integer division

In [5]:
5 // 2

2

## Boolean logic

In [10]:
True

True

In [11]:
False

False

In [12]:
True or False

True

In [13]:
True and False

False

In [14]:
not True

False

In [15]:
1 == 1

True

In [16]:
1 < 0

False

In [17]:
6 < 7 < 8

True

In [7]:
None

## Strings

In [19]:
"This is a string"

'This is a string'

In [20]:
'This too is a string'

'This too is a string'

In [21]:
"""This string has a 
 newline character in it (spans two lines)"""

'This string has a \n newline character in it (spans two lines)'

In [22]:
"Two strings " + "added together"

'Two strings added together'

In [9]:
"strings can be multiplied |" * 3

'strings can be multiplied |strings can be multiplied |strings can be multiplied |'

In [22]:
# String Methods

"hello".index("l")

2

In [23]:
"Breakmeup".partition("me")

('Break', 'me', 'up')

In [21]:
"2 + 2 = {}".format(4)

'2 + 2 = 4'

In [19]:
"There are {x} pilots, and there are {y} pilots, but there are no {x} {y} pilots".format(x="old", y="bold")

'There are old pilots, and there are bold pilots, but there are no old bold pilots'

In [25]:
print("This is how you print in python")

This is how you print in python


## Lists, tuples, and dictionaries

**LISTS**

In [38]:
word_list = ["this", "is", "a", "list"]

In [34]:
# first index is 0!
word_list[0]

'this'

In [35]:
word_list[1]

'is'

In [38]:
# last index
word_list[-1]

'list'

In [39]:
word_list[-1] = "science"

In [40]:
word_list

['this', 'is', 'a', 'science']

In [40]:
word_list.append("party")
print(word_list)

['this', 'is', 'a', 'science', 'party']


In python indexing is called "slicing"

In [54]:
mylist = list(range(10))
print(mylist)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [52]:
# take a slice
mylist[0:5]

[0, 1, 2, 3, 4]

In [53]:
# every other element
mylist[0:8:2]

[0, 2, 4, 6]

**TUPLES**

In [42]:
word_tuple = ("this", "tuple", "is", "invincible")

In [43]:
word_tuple[-1]

'invincible'

In [44]:
word_tuple[-1] = "vincible"

TypeError: 'tuple' object does not support item assignment

**DICTIONARIES**

In [45]:
mouse = {"name": "mickey", "occupation": None, "age": my_var+15}
mouse

{'age': 17, 'name': 'mickey', 'occupation': None}

In [46]:
mouse["age"]

17

In [47]:
print("{name}'s age is {age}".format(name=mouse['name'], age=mouse['age']))

mickey's age is 17


In [48]:
mouse['name']

'mickey'

## A note on mutable and immutable types

**Common immutable types:**
- numbers: int(), float(), complex()
- immutable sequences: str(), tuple(), frozenset(), bytes()

**Common mutable types (almost everything else):**
- mutable sequences: list(), bytearray()
- set type: set()
- mapping type: dict()
- classes, class instances
- etc.

**Examples:**

In [36]:
# immutable type
a = 10 # an integer
b = a
b += 1
print(a)
print(b)

10
11


In [37]:
# mutable type
a = [1, 2, 3] # a list
b = a
b.append(4)
print(a)
print(b)

[1, 2, 3, 4]
[1, 2, 3, 4]


## Functions

In [ ]:
def chant_name(name, N):
    "Yells someone's name, N times"
    return (name.upper() + "! ") * N

In [ ]:
chant_name("Stanley", 10)

Loops and conditionals
-----------------------

In [49]:
for i in word_list:
    print(i)

this
is
a
science
party


In [50]:
sentence = "" # initialize empty string
for i in word_list:
    sentence += " " + i
print(sentence)

 this is a science party


In [51]:
" ".join(word_list) + "!"

'this is a science party!'

In [52]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [54]:
for i in range(10):
    if i < 5:
        print(i)

0
1
2
3
4


In [57]:
good_numbers = [1, 2, 4]
for i in range(10):
    if i in good_numbers:
        print(i)
    else:
        print("bad: {}".format(i))

bad: 0
1
2
bad: 3
4
bad: 5
bad: 6
bad: 7
bad: 8
bad: 9


In [58]:
if mouse['age'] > 20:
    print("old mouse")
elif mouse['age'] < 10:
    print("baby mouse")
else:
    print("awkward teenage mouse")

awkward teenage mouse


List comprehensions
-----------------

In [59]:
[x**2 for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [60]:
[x for x in mouse]

['name', 'age', 'occupation']

In [61]:
[(x, y) for x,y in mouse.items()]

[('name', 'mickey'), ('age', 17), ('occupation', None)]

In [62]:
[(x, x**2) for x in range(20) if x**3 % 3 == 0]

[(0, 0), (3, 9), (6, 36), (9, 81), (12, 144), (15, 225), (18, 324)]

## Arrays
In order to make arrays we need numpy

In [55]:
# standard way of importing numpy
import numpy as np

In [76]:
a = np.arange(1,10,2) # syntax: np.arange(start,end,step)
a

array([1, 3, 5, 7, 9])

In [83]:
b = a
b = np.arange(11,20,2)
print(a)
print(b)

[1 3 5 7 9]
[11 13 15 17 19]


In [84]:
b = a
b += np.ones_like(b)
print(a)
print(b)

[ 2  4  6  8 10]
[ 2  4  6  8 10]


Multi-dim arrays

In [91]:
ra = np.random.randn(5,7)
ra

array([[-0.6052369 ,  0.3975922 , -1.07523457, -0.16339187,  0.70650241,
        -0.8855771 ,  1.49783646],
       [-0.05832944, -0.90913675,  0.76601446, -1.16842662, -1.40870747,
        -0.47505443,  1.6228033 ],
       [-1.90317828, -0.53129351, -1.21721667,  1.00036482,  0.53055172,
         0.49538474,  0.81570531],
       [ 0.24663625,  0.38214938, -1.54900067,  0.04889754, -0.41475065,
        -1.43461838, -0.3525557 ],
       [-1.01390401,  0.91436929, -0.05703492, -0.51327156, -0.72267915,
         1.73936231,  0.206454  ]])

In [92]:
# extract rows 2 & 3, skiping every other column
ra[2:4,::2]

array([[-1.90317828, -1.21721667,  0.53055172,  0.81570531],
       [ 0.24663625, -1.54900067, -0.41475065, -0.3525557 ]])

In [93]:
# dimensions
ra.shape

(5, 7)