# Resources
- Comparison of MATLAB/Python/R commands
    http://mathesaurus.sourceforge.net/matlab-python-xref.pdf
- Jupiter iPython notebook Tutorials              http://nbviewer.jupyter.org/github/twistedhardware/mltutorial/tree/master/notebooks/IPython-Tutorial/

# Bo's notes
These are things that popped out for me as I learned basic ipython3 and remedial numpy.
They may or may not be useful

## What is Jupyter?
Julia + Python + R = Jupyter (aka ipython 3)

It is a a web based IDE that supports over 15 languages

Inspired by Galileo’s notebooks describing Jupiter (4min mark https://www.youtube.com/watch?v=Rc4JQWowG5I)

# Using Markdown
Super fancy comments

Make a new line with 2 spaces at end of line

**Bold** or __Bold__  
*Italic* or _Italic_  

- list item1
- list item2
or
1. list item1
2. list item2

**Links**  
[Scale of Universe](http://scaleofuniverse.com/)

**Images**  
![Dream Brain](http://3.bp.blogspot.com/-QvwoLucHm7w/VawNRtOlB_I/AAAAAAAAKzQ/5CjRwDjKMRQ/s1600/HoffmansBicyle%2Bchalk%2Bdrawing%2Bdeep%2Bdream%2Bbrain.jpg)


LaTex compatible!

$\binom{n}{k} = \frac{n!}{k!(n-k)!}$

## Print
In Python 3 you need parentheses for print, not so in Python 2

In [6]:
print(3+6)

9


## List

In [7]:
mylist = [1,2,3,4,5]
mylist

[1, 2, 3, 4, 5]

In [8]:
# appending to lists is easy
mylist + [6]

[1, 2, 3, 4, 5, 6]

In [10]:
# can't do this!
mylist + 6

TypeError: can only concatenate list (not "int") to list

In [13]:
# mylist = mylist + appended list
mylist += [6,7,8]
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 6, 7, 8, 6, 7, 8]

## Slicing lists
mylist[start:end:step]

In [14]:
mylist[1:5:2]

[2, 4]

In [15]:
mylist[4:]

[5, 6, 7, 8, 6, 7, 8, 6, 7, 8]

In [16]:
## 2nd to last value
mylist[-2]

7

In [17]:
## invert list direction with step of 1
mylist[::-1]

[8, 7, 6, 8, 7, 6, 8, 7, 6, 5, 4, 3, 2, 1]

In [18]:
## invert list direction with step of 2
mylist[::-2]

[8, 6, 7, 8, 6, 4, 2]

In [21]:
myname = 'bolesznikov'
myname

'bolesznikov'

In [23]:
myname[2]

'l'

## Division
Python2 assumed division should return integers, Python3 returns floating point value

In [24]:
5.8/2

2.9

In [25]:
## integer division
5.8//2

2.0

In [26]:
# exponents
2**3

8

In [28]:
import math
math.factorial(4)

24

# Numpy

In [29]:
import numpy as np

In [30]:
np.arange(1,10,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [32]:
x = np.arange(1,10,0.5)

In [33]:
x.size

18

## multidim Array

In [38]:
# 1 dim
np.array([1,10,0.5])

array([  1. ,  10. ,   0.5])

In [40]:
# multi dim
np.array([[1,10,0.5],[1,10,0.5]])

array([[  1. ,  10. ,   0.5],
       [  1. ,  10. ,   0.5]])

In [42]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [43]:
# Linspace syntax requires num=4
np.linspace(2,4,num=4)

array([ 2.        ,  2.66666667,  3.33333333,  4.        ])

In [44]:
# syntax for making random numbers is cumbersome
np.random.random((2,3))

array([[ 0.9174967 ,  0.75203932,  0.14377456],
       [ 0.87924107,  0.27887909,  0.5364797 ]])

In [46]:
ra = np.random.random((2,3))
np.max(ra,axis=0)

array([ 0.97475679,  0.75817063,  0.8864631 ])

In [47]:
## 0 gives rows, 1 gives columns

In [48]:
# flatten array
np.ravel(ra)

array([ 0.71446832,  0.75817063,  0.8864631 ,  0.97475679,  0.4206047 ,
        0.43497961])

In [49]:
# much less elegant than MATLAB syntax ra(:)

## Slicing arrays (known as "indexing" in MATLAB)

In [52]:
ra = np.random.random((5,5))

In [53]:
ra

array([[ 0.41049804,  0.60750395,  0.20004089,  0.81815467,  0.23858286],
       [ 0.41986009,  0.21492342,  0.15420876,  0.50273141,  0.26719051],
       [ 0.56187921,  0.60113046,  0.08500103,  0.28238845,  0.74761037],
       [ 0.03834715,  0.48128217,  0.39049352,  0.88105044,  0.90850705],
       [ 0.44454865,  0.98519555,  0.81302339,  0.13164275,  0.42382996]])

In [54]:
# extract rows 2 & 3, skiping every other column
ra[2:4,::2]

array([[ 0.56187921,  0.08500103,  0.74761037],
       [ 0.03834715,  0.39049352,  0.90850705]])

In [59]:
ra.shape[0]

5

# Some useful numpy functions

- np.ones_like(x)
    Return an array of ones with the same shape and type as array x. Similar functions zero_like, empty_like
- select(condlist,choicelist,default=0)
    allows rapid construction of a function which returns an array of results based on a list of conditions
    

## Need to know

- Initializing variables: How to populate elements of a matrix with for loop
- Summing along dimensions
- Dividing matrix by 1d array. Does Python automaticaly adjust transpose?